export { default as LoginForm } from './login-form'
export { default as SearchForm } from './search-form'
export { default as ReviewForm } from './review-form'
export { default as RegisterForm } from './register-form'
export { default as UpdateProfileForm } from './update-profile-form'
export { default as ChangePasswordForm } from './change-password-form'
export { default as ForgotPasswordForm } from './forgot-password-form'
